class ExampleAuthBasicJwtAction extends baseAction {
  async executeMethod() {
    /*
      AUTHENTICATION USING JWT EXAMPLE

      Prerequisites:
      1. In config->config.json set the following:
          "AUTH_MODE": "JWT",             (NOTE: JWT and JWT_SQL are the two modes available)
          "JWT_SECRET": "my_secret_key"   (NOTE: This is secret key used for generate JWT Token)
          "JWT_ID_KEY": "user_id"         (NOTE: This is data/payload that was used while creating JWT Token)
          "DB_ID_KEY": "user_id"          (NOTE: Name of argument which return from JWT Token)
        
      2. In init.js set this.pkgInitializer.isSecured: true.   
        (NOTE: This is for expecting access_token from request header )
      
      Steps:  
      1. In postman select example/authBasicJwt in the demo-project collection, then select Headers tab.
      2. Pass the token in the header of the request as access_token, which is generated by the example/authBasicJwtCreate API.
      3. Njs2 itself decrypts the access_token and returns the data, i.e. user_id, in the "userObj" object.
    */

    let { userObj } = this;

    this.setResponse("SUCCESS");
    return { user_id: userObj.user_id };
  }
}
module.exports = ExampleAuthBasicJwtAction;
